### ISSUE TITLE
E~F Android 4.3 下 :focus 与兄弟选择符一起使用的bug

### ISSUE THREAD

**Issue by gehuangyi20** [doyoe/css-handbook#78]
以下这段代码在Android 4.3 下没有任何效果，三星手机实测

```css
input:focus ~ .test{
    background-color: red
}
```

Note: 我是看了这个链接里面描述的 “:checked与兄弟选择符一起使用的bug” 得到启发的
https://github.com/doyoe/trip#user-content-checked-sibling-bug
