### ISSUE TITLE
currentColor兼容性有误

### ISSUE THREAD

**Issue by ydq** [doyoe/css-handbook#93]
在[caniuse](http://caniuse.com/#search=currentColor)上显示currentColor属性只在IE9以及以上版本才被支持。
其次demo也应该是  

> div {
> 	border: 1px solid currentColor;
> 	color: red;
> }

**Comment by doyoe** [comment]
可能是我的表述有点问题，其实我想说的是：

```css
div {
	border: 1px solid;
	color: red;
}
```

实际上等价于：

```css
div {
	border: 1px solid currentColor;
	color: red;
}
```

当 `border` 不显示的指定具体的色值时，其使用值为 `color` 属性的计算值。所以，如果你希望边框色和文本色一致，边框色可以忽略不定义。不过在 `CSS3` 中为了更好的规范用法，提供了一个 `currentColor` 关键字来承担这个角色。这2者其实是等价的，不过手册的兼容性视图对针对 `currentColor` 关键字的，而不是针对这个特性，使用确实写错了。

感谢帮忙纠错 :)
