### ISSUE TITLE
关于box-shadow 属性的阴影外延值

### ISSUE THREAD

**Issue by jackPanyj** [doyoe/css-handbook#99]
``` css
div.box-shadow {
    width: 100px;
    height: 100px;
    border: 10px solid teal;
    box-shadow: 0 0 0 -30px pink;
}
```
手册上说可正可负， 负数有什么作用吗 ，本身box-shadow 有 inset属性的，没有测试出负数有什么效果。

[codepen链接](http://codepen.io/jackpan/pen/mPYYEM)
